sudo: false
language: python

jobs:
  include:
    - stage: pretest
      env: TOXENV=flake8
      python: 3.6
    - env: TOXENV=pylint
      python: 3.6

    # Create alias named test for environments
    - &test
      stage: test
      services: mongodb
      before_script:
        - sleep 15
        - mongo orion_test --eval 'db.createUser({user:"user",pwd:"pass",roles:["readWrite"]});'
      after-success:
        - tox -e final-coverage
        - tox -e codecov
      env: TOXENV=py36
      python: 3.6

    # Reuse the test stage setup with a different environment each time
    - <<: *test
      env: TOXENV=py37
      python: 3.7
    - <<: *test
      env: TOXENV=py38
      python: 3.8
      dist: bionic
      sudo: true
    - stage: packaging
      env: TOXENV=packaging
      python: 3.6

before_install:
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install -y swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig

install:
  - pip install tox
script:
  - tox